version: "3.7"

services:
  php-fpm_patterns:
    build:
      context: docker
      dockerfile: Dockerfile
    working_dir: /code/patterns
    ports:
    - "8077:8077"
    volumes:
      - ./code:/code